### ISSUE TITLE
"AssertionError: articlepath must end with /$1"

### ISSUE THREAD

**Issue by guaka** [guaka/pywikibot-extras#8]
pywikibot complains:
"AssertionError: articlepath must end with /$1"

It's not clear to me where to report this upstream. Or how to best resolve it. I will try if uncommenting the assertion does the trick.

```
Traceback (most recent call last):
...p.full_url()...
  File "pywikibot/page.py", line 303, in full_url
    return self.site.base_url(self.site.article_path +
  File "pywikibot/site.py", line 1915, in article_path
    'articlepath must end with /$1'
AssertionError: articlepath must end with /$1
```

**Comment by guaka** [comment]
This happens with a wiki with URLs like `/wiki/index.php?title=Page`. Same code works fine on another server with `wiki/index.php/Page`.
